import Vue from 'vue'
import VueRouter from 'vue-router'
Vue.use(VueRouter)

const routes = [
  {
    path:'/',
    redirect:'/login'
  },
  {
    path:'/login',
    name:'login',
    component:()=>import('../view/element/UserLogin.vue')
  },
  {
    path:'/register',
    name:'register',
    component:()=>import('../view/element/UserRegister.vue')
  },
  {
    path:'/students',
    name:'students',
    component:()=>import('../view/students/StudentDeclarant.vue')
  },
  {
    path:'/personal',
    name:'personal',
    component:()=>import('../view/students/StudentsPersonlInformation.vue')
  },
  {
    path:'/declare',
    name:'declare',
    component:()=>import('../view/students/DeclarationInterface.vue')
  },
  {
    path:'/progress',
    name:'progress',
    component:()=>import('../view/element/TeacherProgressBar.vue')
  },
  {
    path:'/teachers',
    name:'teachers',
    component:()=>import('../view/teachers/TeachersDeclarant.vue')
  },
  {
    path:'/administrator',
    name:'administrator',
    component:()=>import('../view/adminstrator/SystemAdministrator.vue')
  },
  {
    path:'/management',
    name:'management',
    component:()=>import('../view/adminstrator/ProjectPresentation.vue')
  },
  {
    path:'/manage',
    name:'manage',
    component:()=>import('../view/adminstrator/ProjectManagement.vue')
  },
  {
    path:'/change',
    name:'ProjectChange',
    component:()=>import('../view/adminstrator/ProjectChange.vue')
  },
  {
    path:'/shenbao',
    name:'shenbao',
    component:()=>import('../view/students/DeclareInterface.vue')
  },
  {
    path:'/projectcheck',
    name:'ProjectCheck',
    component:()=>import('../view/students/ProjectCheck.vue')
  },
  {
    path:'/review',
    name:'review',
    component:()=>import('../view/teachers/ZhiDaoProject.vue')
  },
  {
    path:'/teacherspersonal',
    name:'teacherspersonal',
    component:()=>import('../view/teachers/TeachersPersonal.vue')
  },
  {
    path:'/adminpersonal',
    name:'adminpersonal',
    component:()=>import('../view/adminstrator/AdminPersonal.vue')
  },
  {
    path:'/reviewList',
    name:'reviewList',
    component:()=>import('../view/teachers/ReviewList.vue')
  },
  {
    path:'/studentprogress',
    name:'studentprogress',
    component:()=>import('../view/element/StudentsProgressBar.vue')
  },
  {
    path:'/teacherdeclare',
    name:'teacherdeclare',
    component:()=>import('../view/teachers/TeacherDeclaration.vue')
  },
  {
    path:'/studentsnotice',
    name:'studentsnotice',
    component:()=>import('../view/element/StudentsNotice.vue')
  },
  {
    path:'/teachersnotice',
    name:'teachersnotice',
    component:()=>import('../view/element/TeacherNotice.vue')
  },
  {
    path:'/all',
    name:'AllDeclaration',
    component:()=>import('../view/adminstrator/AllDeclaration.vue')
  },
  {
    path:'/teachermanagement',
    name:'TeacherManagement',
    component:()=>import('../view/adminstrator/TeacherManagement.vue')
  },
  {
    path:'/studentsmanagement',
    name:'StudentsManagement',
    component:()=>import('../view/adminstrator/StudentsManagement.vue')
  },
  {
    path:'/edit',
    name:'UserEdit',
    component:()=>import('../view/adminstrator/UserEdit.vue')
  },
  {
    path:'/xiangqing',
    name:'DeclarationBook',
    component:()=>import('../view/adminstrator/DeclarationBook.vue')
  },
  {
    path:'/zhiding',
    name:'ZhiDing',
    component:()=>import('../view/adminstrator/ZhiDing.vue')
  },
  {
    path:'/pingshen',
    name:'PingShenProject',
    component:()=>import('../view/teachers/PingShenProject.vue')
  },
  {
    path:'/pingshenlist',
    name:'PingShenList',
    component:()=>import('../view/teachers/PingShenList.vue')
  },
  {
    path:'/alldeclaration',
    name:'DeclarationsList',
    component:()=>import('../view/adminstrator/DeclarationsList.vue')
  },

]
const router = new VueRouter({
  mode:'history',
  routes
})
export default router
